version: '3'

services:
  db: 
    container_name: postgrest-db
    image: postgres:latest
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13960
      POSTGRES_DB: ejemplo
  pg-admin:
    depends_on:
      - db
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: 13960
      PGADMIN_DEFAULT_EMAIL: Luis@gmail.com
      

volumes:
  postgres-db:
  external: true